# Generated by Django 4.2.7 on 2023-12-06 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('price', models.FloatField(blank=True, default=0.0, verbose_name='Prix du produit')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image du produit')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(blank=True, default=0, verbose_name='Stock du produit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('reference', models.CharField(max_length=128)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Créer', max_length=255)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
